name: appmp3_musicbeat
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  provider: ^6.1.1


  just_audio: ^0.9.36
  audio_service: ^0.18.12


  http: ^1.1.0
  dio: ^5.4.0
  path_provider: ^2.1.1


  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1


  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/icon/
  generate: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
